export const CATEGORIAS_SERVICO = [
  "Desenvolvimento Web",
  "Design Gráfico",
  "Marketing Digital",
  "Redação e Tradução",
  "Edição de Vídeo",
  "Suporte Administrativo",
  "Atendimento ao Cliente",
  "Gestão de Projetos",
  "Desenvolvimento Mobile",
  "Consultoria",
  "Animais",
  "Serviços Domésticos",
  "Tecnologia",
  "Educação",
  "Outros"
];

export const HABILIDADES_PROFISSIONAIS = [
  "React",
  "Node.js",
  "Python",
  "JavaScript",
  "UI/UX Design",
  "Figma",
  "Photoshop",
  "SEO",
  "Copywriting",
  "Inglês",
  "Espanhol",
  "Gestão de Tráfego",
  "AWS",
  "Docker",
  "Atendimento B2B",
  "Atendimento B2C",
  "Edição Premiere",
  "HTML/CSS",
  "Adestramento Básico",
  "Cuidados com Pet",
  "Passeador de Cães"
].sort();
