# Generated by Django 6.0.3 on 2026-04-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user', 'Usuário'), ('ad', 'Anúncio')], max_length=20)),
                ('target_id', models.CharField(max_length=50)),
                ('target_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('resolved', 'Resolvido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
