# Generated by Django 6.0.3 on 2026-04-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('procedente', 'Procedente'), ('improcedente', 'Improcedente')], default='pending', max_length=20),
        ),
    ]
