# Generated by Django 6.0.3 on 2026-05-04 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ad_atualizado_em_ad_criado_em_ad_deletado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.BigIntegerField(blank=True, null=True)),
                ('anuncio_id', models.BigIntegerField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='pendente', max_length=50, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True, null=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='core.ad')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidaturas',
            },
        ),
    ]
