# Generated by Django 6.0.3 on 2026-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_verificacaoemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacaoemail',
            name='criado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
