# Generated by Django 6.0.3 on 2026-06-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_verificacaoemail_criado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcordoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_acordo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_acordado', models.FloatField(blank=True, null=True)),
                ('conclusao_prevista', models.DateField(blank=True, null=True)),
                ('titulo_anuncio', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao_servico', models.TextField(blank=True, null=True)),
                ('unidade_valor', models.CharField(blank=True, max_length=50, null=True)),
                ('proposta_aceita', models.TextField(blank=True, null=True)),
                ('nome_contratante', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_prestador', models.CharField(blank=True, max_length=255, null=True)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='core.candidatura')),
            ],
            options={
                'db_table': 'acordo_servico',
            },
        ),
    ]
