# Generated by Django 6.0.3 on 2026-06-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_acordoservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordoservico',
            name='justificativa_alteracao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acordoservico',
            name='proposta_conclusao_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acordoservico',
            name='proposta_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acordoservico',
            name='proposto_valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acordoservico',
            name='solicitado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='acordoservico',
            name='tem_solicitacao',
            field=models.BooleanField(default=False),
        ),
    ]
