# Generated by Django 6.0.3 on 2026-07-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_acordoservico_justificativa_alteracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('verificado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'instituicoes_ensino',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=255)),
                ('nome_certificado', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('exibir_perfil', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.userprofile')),
            ],
            options={
                'db_table': 'certificados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
