from django.db import migrations


INSTITUICOES = [
    "USP - Universidade de São Paulo",
    "UNICAMP - Universidade Estadual de Campinas",
    "UFMG - Universidade Federal de Minas Gerais",
    "UFRJ - Universidade Federal do Rio de Janeiro",
    "UNESP - Universidade Estadual Paulista",
    "UFRGS - Universidade Federal do Rio Grande do Sul",
    "UFSC - Universidade Federal de Santa Catarina",
    "UFPR - Universidade Federal do Paraná",
    "UnB - Universidade de Brasília",
    "UFPE - Universidade Federal de Pernambuco",
    "UFC - Universidade Federal do Ceará",
    "UFBA - Universidade Federal da Bahia",
    "UFSM - Universidade Federal de Santa Maria",
    "UFU - Universidade Federal de Uberlândia",
    "UFSCAR - Universidade Federal de São Carlos",
    "UFF - Universidade Federal Fluminense",
    "UFPA - Universidade Federal do Pará",
    "UFAM - Universidade Federal do Amazonas",
    "FURG - Universidade Federal do Rio Grande",
    "UFPB - Universidade Federal da Paraíba",
    "UFRN - Universidade Federal do Rio Grande do Norte",
    "UFMA - Universidade Federal do Maranhão",
    "UFAL - Universidade Federal de Alagoas",
    "UFSE - Universidade Federal de Sergipe",
    "UFMT - Universidade Federal de Mato Grosso",
    "UFMS - Universidade Federal de Mato Grosso do Sul",
    "UFG - Universidade Federal de Goiás",
    "UFES - Universidade Federal do Espírito Santo",
    "UFPI - Universidade Federal do Piauí",
    "UFAC - Universidade Federal do Acre",
    "UFRR - Universidade Federal de Roraima",
    "UNIFAP - Universidade Federal do Amapá",
    "UFT - Universidade Federal do Tocantins",
    "PUC-SP - Pontifícia Universidade Católica de São Paulo",
    "PUC-RJ - Pontifícia Universidade Católica do Rio de Janeiro",
    "PUC-RS - Pontifícia Universidade Católica do Rio Grande do Sul",
    "PUC-MG - Pontifícia Universidade Católica de Minas Gerais",
    "PUC-Campinas - Pontifícia Universidade Católica de Campinas",
    "PUC-PR - Pontifícia Universidade Católica do Paraná",
    "Mackenzie - Universidade Presbiteriana Mackenzie",
    "FGV - Fundação Getulio Vargas",
    "INSPER - Insper Instituto de Ensino e Pesquisa",
    "ITA - Instituto Tecnológico de Aeronáutica",
    "IME - Instituto Militar de Engenharia",
    "UNIFESP - Universidade Federal de São Paulo",
    "UTFPR - Universidade Tecnológica Federal do Paraná",
    "CEFET-MG - Centro Federal de Educação Tecnológica de Minas Gerais",
    "CEFET-RJ - Centro Federal de Educação Tecnológica do Rio de Janeiro",
    "IFSP - Instituto Federal de São Paulo",
    "IFRJ - Instituto Federal do Rio de Janeiro",
    "IFMG - Instituto Federal de Minas Gerais",
    "IFRS - Instituto Federal do Rio Grande do Sul",
    "IFSC - Instituto Federal de Santa Catarina",
    "IFBA - Instituto Federal da Bahia",
    "IFPE - Instituto Federal de Pernambuco",
    "IFCE - Instituto Federal do Ceará",
    "UERJ - Universidade do Estado do Rio de Janeiro",
    "UNIRIO - Universidade Federal do Estado do Rio de Janeiro",
    "UENF - Universidade Estadual do Norte Fluminense",
    "UEZO - Universidade Estadual da Zona Oeste",
    "UEL - Universidade Estadual de Londrina",
    "UEM - Universidade Estadual de Maringá",
    "UEPG - Universidade Estadual de Ponta Grossa",
    "UNIOESTE - Universidade Estadual do Oeste do Paraná",
    "UECE - Universidade Estadual do Ceará",
    "UEFS - Universidade Estadual de Feira de Santana",
    "UESC - Universidade Estadual de Santa Cruz",
    "UESB - Universidade Estadual do Sudoeste da Bahia",
    "UVA - Universidade Estadual do Vale do Acaraú",
    "UNIT - Universidade Tiradentes",
    "UNISINOS - Universidade do Vale do Rio dos Sinos",
    "UNISUL - Universidade do Sul de Santa Catarina",
    "UNIVALI - Universidade do Vale do Itajaí",
    "UNIVILLE - Universidade da Região de Joinville",
    "UNOESC - Universidade do Oeste de Santa Catarina",
    "UPF - Universidade de Passo Fundo",
    "UCS - Universidade de Caxias do Sul",
    "UNISC - Universidade de Santa Cruz do Sul",
    "UNIJUÍ - Universidade Regional do Noroeste do Estado do RS",
    "UNIPAMPA - Universidade Federal do Pampa",
    "UFCSPA - Universidade Federal de Ciências da Saúde de Porto Alegre",
    "UFRB - Universidade Federal do Recôncavo da Bahia",
    "UFOB - Universidade Federal do Oeste da Bahia",
    "UFSB - Universidade Federal do Sul da Bahia",
    "UFV - Universidade Federal de Viçosa",
    "UFJF - Universidade Federal de Juiz de Fora",
    "UFLA - Universidade Federal de Lavras",
    "UFOP - Universidade Federal de Ouro Preto",
    "UFSJ - Universidade Federal de São João del-Rei",
    "UFTM - Universidade Federal do Triângulo Mineiro",
    "UNIFEI - Universidade Federal de Itajubá",
    "UFABC - Universidade Federal do ABC",
    "UFGD - Universidade Federal da Grande Dourados",
    "UFCA - Universidade Federal do Cariri",
    "UNILAB - Universidade da Integração Internacional da Lusofonia Afro-Brasileira",
    "UNILA - Universidade Federal da Integração Latino-Americana",
    "UNIVASF - Universidade Federal do Vale do São Francisco",
    "Coursera",
    "Udemy",
    "Alura",
    "Rocketseat",
    "Digital Innovation One (DIO)",
    "Ada",
    "Cubos Academy",
    "Trybe",
    "Labenu",
    "Kenzie Academy Brasil",
    "Let's Code",
    "EBAC - Escola Britânica de Artes Criativas",
    "SENAI - Serviço Nacional de Aprendizagem Industrial",
    "SENAC - Serviço Nacional de Aprendizagem Comercial",
    "SESI - Serviço Social da Indústria",
    "SENAR - Serviço Nacional de Aprendizagem Rural",
    "SEBRAE - Serviço Brasileiro de Apoio às Micro e Pequenas Empresas",
    "CEUB - Centro Universitário de Brasília",
    "UNICEUB - Centro Universitário de Brasília",
    "FECAP - Fundação Escola de Comércio Álvares Penteado",
    "IBMEC",
    "FAAP - Fundação Armando Alvares Penteado",
    "ESPM - Escola Superior de Propaganda e Marketing",
    "FMU - Centro Universitário das Faculdades Metropolitanas Unidas",
    "UNINOVE - Universidade Nove de Julho",
    "ANHEMBI MORUMBI - Universidade Anhembi Morumbi",
    "SÃO JUDAS - Universidade São Judas Tadeu",
    "UNIP - Universidade Paulista",
    "UNICSUL - Universidade Cruzeiro do Sul",
    "UNG - Universidade Guarulhos",
    "UNISA - Universidade Santo Amaro",
    "UMC - Universidade de Mogi das Cruzes",
    "USF - Universidade São Francisco",
    "UNIVAP - Universidade do Vale do Paraíba",
    "UNISO - Universidade de Sorocaba",
    "UNIMEP - Universidade Metodista de Piracicaba",
    "PUC-GO - Pontifícia Universidade Católica de Goiás",
    "UFMT - Universidade Federal de Mato Grosso",
    "FAMAT - Faculdade de Matemática",
]


def seed_instituicoes(apps, schema_editor):
    InstituicaoEnsino = apps.get_model('core', 'InstituicaoEnsino')
    for nome in INSTITUICOES:
        InstituicaoEnsino.objects.get_or_create(nome=nome, defaults={'verificado': True})


def reverse(apps, schema_editor):
    InstituicaoEnsino = apps.get_model('core', 'InstituicaoEnsino')
    InstituicaoEnsino.objects.filter(nome__in=INSTITUICOES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_perfil_certificados_instituicoes'),
    ]

    operations = [
        migrations.RunPython(seed_instituicoes, reverse),
    ]
