# Generated by Django 6.0.3 on 2026-07-02 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mais_instituicoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('atual', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='core.userprofile')),
            ],
            options={
                'db_table': 'experiencias',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
