# Generated by Django 6.0.3 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_cidade_userprofile_email_visivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
