# Generated by Django 6.0.3 on 2026-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
