# Generated by Django 6.0.3 on 2026-07-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='redes_sociais',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
