# Generated by Django 6.0.3 on 2026-07-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_userprofile_url_userprofile_redes_sociais'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/'),
        ),
    ]
