# Generated by Django 6.0.3 on 2026-07-24 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_alteracoes_pendentes(apps, schema_editor):
    AcordoServico = apps.get_model('core', 'AcordoServico')
    SolicitacaoAlteracao = apps.get_model('core', 'SolicitacaoAlteracaoAcordo')

    for acordo in AcordoServico.objects.filter(tem_solicitacao=True).select_related(
        'candidatura__user',
        'candidatura__ad__author',
    ):
        candidatura = acordo.candidatura
        if not candidatura:
            continue
        if acordo.solicitado_por == 'freelancer':
            solicitante_id = candidatura.user_id
        else:
            solicitante_id = candidatura.ad.author_id if candidatura.ad_id else None
        if not solicitante_id:
            continue

        SolicitacaoAlteracao.objects.get_or_create(
            acordo_id=acordo.id,
            status='pendente',
            defaults={
                'solicitante_id': solicitante_id,
                'papel_solicitante': acordo.solicitado_por or 'contratante',
                'justificativa': acordo.justificativa_alteracao or 'Solicitação migrada.',
                'valor_anterior': acordo.valor_acordado,
                'valor_proposto': acordo.proposto_valor,
                'descricao_anterior': acordo.descricao_servico,
                'descricao_proposta': acordo.proposta_descricao,
                'conclusao_anterior': acordo.conclusao_prevista,
                'conclusao_proposta': acordo.proposta_conclusao_prevista,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_avaliacao_acordo_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acordoservico',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordoservico',
            name='status_acordo',
            field=models.CharField(choices=[('Pendente Pagamento', 'Pagamento pendente'), ('Ativo', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente Pagamento', max_length=50),
        ),
        migrations.CreateModel(
            name='SolicitacaoAlteracaoAcordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_solicitante', models.CharField(choices=[('freelancer', 'Freelancer'), ('contratante', 'Contratante')], max_length=20)),
                ('justificativa', models.TextField()),
                ('valor_anterior', models.FloatField(blank=True, null=True)),
                ('valor_proposto', models.FloatField(blank=True, null=True)),
                ('descricao_anterior', models.TextField(blank=True, null=True)),
                ('descricao_proposta', models.TextField(blank=True, null=True)),
                ('conclusao_anterior', models.DateField(blank=True, null=True)),
                ('conclusao_proposta', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('decidido_em', models.DateTimeField(blank=True, null=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_alteracao', to='core.acordoservico')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_acordo_decididas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alteracoes_acordo_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitacoes_alteracao_acordo',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', '-criado_em'], name='alter_status_criado_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('acordo',), name='alteracao_pendente_unica_acordo')],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoCancelamentoAcordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel_solicitante', models.CharField(choices=[('freelancer', 'Freelancer'), ('contratante', 'Contratante')], max_length=20)),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('resposta_admin', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('analisado_em', models.DateTimeField(blank=True, null=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cancelamento', to='core.acordoservico')),
                ('analisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelamentos_acordo_analisados', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancelamentos_acordo_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitacoes_cancelamento_acordo',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', '-criado_em'], name='cancel_status_criado_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pendente')), fields=('acordo',), name='cancelamento_pendente_unico_acordo')],
            },
        ),
        migrations.RunPython(
            migrar_alteracoes_pendentes,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
