# Generated by Django 6.0.3 on 2026-08-05 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_unificar_identificador_pagamentos_simulados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('candidatura', 'Candidatura'), ('acordo', 'Acordo'), ('avaliacao', 'Avaliação'), ('pagamento', 'Pagamento'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacoes',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'lida'], name='notif_user_lida_idx')],
            },
        ),
    ]
