# Generated by Django 6.0.3 on 2026-09-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ad_description_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
