# Generated by Django 6.0.3 on 2026-09-04 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_userprofile_banner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=2000)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat', to='core.acordoservico')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_chat_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagens_chat',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['acordo', 'criado_em'], name='chat_acordo_criado_idx'), models.Index(fields=['acordo', 'lida'], name='chat_acordo_lida_idx')],
            },
        ),
    ]
