# Generated by Django 6.0.3 on 2026-09-07 16:30

from django.db import migrations, models

BIO_PADRAO_ANTIGA = (
    "Sou um adestrador certificado e apaixonado por animais. Tenho anos de "
    "experiência lidando com comportamento canino, ajudando donos a "
    "entenderem e treinarem seus cães com reforço positivo."
)


def limpar_bio_padrao(apps, schema_editor):
    """
    Remove o texto padrão indevido que ficava gravado em usuários que nunca
    escreveram uma bio (o default antigo do campo). Só apaga quando o texto
    é exatamente igual ao default antigo, para não apagar bios reais que o
    usuário tenha escrito por conta própria.
    """
    UserProfile = apps.get_model('core', 'UserProfile')
    UserProfile.objects.filter(bio=BIO_PADRAO_ANTIGA).update(bio='')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_novos_criterios_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(
            limpar_bio_padrao,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
