# Generated by Django 6.0.3 on 2026-09-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_corrige_bio_padrao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartaousuario',
            name='cartao_usuario_bandeira_final_unico',
        ),
        migrations.DeleteModel(
            name='CartaoUsuario',
        ),
    ]
