# Generated by Django 6.0.3 on 2026-09-13 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_cartaousuario_cartao_usuario_bandeira_final_unico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to='core.ad'),
        ),
    ]
