# Generated by Django 6.0.3 on 2026-09-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_notificacao_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='papel',
            field=models.CharField(blank=True, choices=[('freelancer', 'Freelancer'), ('empresa', 'Empresa')], max_length=20, null=True),
        ),
    ]
