# Generated by Django 6.0.3 on 2026-09-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_notificacao_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_cancel_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
