# Generated by Django 6.0.3 on 2026-09-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_userprofile_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aceitou_termos_empresa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nome_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='porte_empresa',
            field=models.CharField(blank=True, choices=[('autonomo', 'Autônomo'), ('micro', 'Micro (até 9 funcionários)'), ('pequena', 'Pequena (10 a 49)'), ('media', 'Média (50 a 249)'), ('grande', 'Grande (250+)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ramo_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site_empresa',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_empresa',
            field=models.CharField(blank=True, choices=[('pessoa', 'Pessoa física contratante'), ('cnpj', 'Empresa com CNPJ')], max_length=20, null=True),
        ),
    ]
