# Generated by Django 6.0.3 on 2026-09-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_userprofile_subscription_cancel_at'),
        ('core', '0038_userprofile_aceitou_termos_empresa_and_more'),
    ]

    operations = [
    ]
