# Generated by Django 6.0.3 on 2026-09-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userprofile_aceitou_termos_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='deletado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='deletado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='deletado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='deletado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='mensagemchat',
            name='deletado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='deletado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
