# Generated by Django 6.0.3 on 2026-09-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_soft_delete_conteudo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aceitou_termos_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
