# Generated by Django 6.0.3 on 2026-09-21 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_merge_20260918_1931'),
        ('core', '0040_userprofile_aceitou_termos_freelancer'),
    ]

    operations = [
    ]
