# Generated by Django 6.0.3 on 2026-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20260921_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ramos_atuacao',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
