# Generated by Django 6.0.3 on 2026-09-30 19:05

from datetime import date

from django.db import migrations, models


def preencher_conclusao_prevista(apps, schema_editor):
    """Acordos antigos nasceram sem `conclusao_prevista`: usa o prazo da vaga."""
    AcordoServico = apps.get_model('core', 'AcordoServico')
    pendentes = AcordoServico.objects.filter(
        conclusao_prevista__isnull=True,
        candidatura__ad__deadline__isnull=False,
    ).select_related('candidatura__ad')
    for acordo in pendentes:
        try:
            prazo = date.fromisoformat(str(acordo.candidatura.ad.deadline)[:10])
        except ValueError:
            continue
        AcordoServico.objects.filter(pk=acordo.pk).update(conclusao_prevista=prazo)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_papeis_fixos'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordoservico',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acordoservico',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, choices=[('prazo_pagamento', 'Prazo de pagamento expirado'), ('moderacao', 'Cancelado pela moderação')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='solicitacaocancelamentoacordo',
            name='motivo',
            field=models.CharField(choices=[('nao_compareceu', 'O freelancer não compareceu'), ('nao_entregou', 'O serviço não foi entregue'), ('fora_do_combinado', 'O serviço foi entregue fora do combinado'), ('desistencia', 'Desistência de uma das partes'), ('outro', 'Outro motivo')], default='outro', max_length=30),
        ),
        migrations.AlterField(
            model_name='acordoservico',
            name='status_acordo',
            field=models.CharField(choices=[('Pendente Pagamento', 'Pagamento pendente'), ('Ativo', 'Em andamento'), ('Aguardando confirmação', 'Aguardando confirmação'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente Pagamento', max_length=50),
        ),
        migrations.RunPython(preencher_conclusao_prevista, reverse_code=migrations.RunPython.noop),
    ]
