# Generated by Django 6.0.3 on 2026-09-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_ciclo_acordo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocancelamentoacordo',
            name='estornado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitacaocancelamentoacordo',
            name='parte_infratora',
            field=models.CharField(blank=True, choices=[('freelancer', 'Freelancer'), ('contratante', 'Contratante')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pontos_infracao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
