# Generated by Django 6.0.3 on 2026-09-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_moderacao_infracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ano_fundacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='como_trabalha',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responsavel_cargo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='responsavel_nome',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='servicos_contratados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
